celebrities = [
    {"name": "Cristiano Ronaldo", "follower_count": 615, "profession": "Footballer"},
    {"name": "Lionel Messi", "follower_count": 489, "profession": "Footballer"},
    {"name": "Selena Gomez", "follower_count": 429, "profession": "Singer/Actress"},
    {"name": "Kylie Jenner", "follower_count": 399, "profession": "Reality TV Star/Businesswoman"},
    {"name": "Dwayne Johnson", "follower_count": 392, "profession": "Actor/Producer"},
    {"name": "Ariana Grande", "follower_count": 380, "profession": "Singer/Actress"},
    {"name": "Kim Kardashian", "follower_count": 364, "profession": "Reality TV Star/Businesswoman"},
    {"name": "Beyoncé", "follower_count": 319, "profession": "Singer"},
    {"name": "Khloé Kardashian", "follower_count": 311, "profession": "Reality TV Star"},
    {"name": "Nike", "follower_count": 306, "profession": "Brand"},
    {"name": "Kendall Jenner", "follower_count": 294, "profession": "Model"},
    {"name": "Justin Bieber", "follower_count": 292, "profession": "Singer"},
    {"name": "National Geographic", "follower_count": 283, "profession": "Media"},
    {"name": "Taylor Swift", "follower_count": 279, "profession": "Singer"},
    {"name": "Virat Kohli", "follower_count": 266, "profession": "Cricketer"},
    {"name": "Jennifer Lopez", "follower_count": 252, "profession": "Singer/Actress"},
    {"name": "Nicki Minaj", "follower_count": 228, "profession": "Rapper"},
    {"name": "Kourtney Kardashian", "follower_count": 224, "profession": "Reality TV Star"},
    {"name": "Miley Cyrus", "follower_count": 216, "profession": "Singer/Actress"},
    {"name": "Neymar Jr", "follower_count": 214, "profession": "Footballer"},
    {"name": "Katy Perry", "follower_count": 206, "profession": "Singer"},
    {"name": "Zendaya", "follower_count": 184, "profession": "Actress"},
    {"name": "Kevin Hart", "follower_count": 179, "profession": "Comedian/Actor"},
    {"name": "Cardi B", "follower_count": 169, "profession": "Rapper"},
    {"name": "Demi Lovato", "follower_count": 157, "profession": "Singer/Actress"},
    {"name": "LeBron James", "follower_count": 156, "profession": "Basketball Player"},
    {"name": "Rihanna", "follower_count": 152, "profession": "Singer/Businesswoman"},
    {"name": "Chris Brown", "follower_count": 144, "profession": "Singer"},
    {"name": "Ellen DeGeneres", "follower_count": 139, "profession": "TV Host"},
    {"name": "Drake", "follower_count": 138, "profession": "Rapper"},
    {"name": "Billie Eilish", "follower_count": 110, "profession": "Singer"},
    {"name": "NASA", "follower_count": 96, "profession": "Space Agency"},
    {"name": "Shawn Mendes", "follower_count": 95, "profession": "Singer"},
    {"name": "Emma Watson", "follower_count": 94, "profession": "Actress"},
    {"name": "Priyanka Chopra", "follower_count": 89, "profession": "Actress"},
    {"name": "Shakira", "follower_count": 88, "profession": "Singer"},
    {"name": "David Beckham", "follower_count": 85, "profession": "Footballer"},
    {"name": "Will Smith", "follower_count": 84, "profession": "Actor"},
    {"name": "Gal Gadot", "follower_count": 83, "profession": "Actress"},
    {"name": "Vin Diesel", "follower_count": 82, "profession": "Actor"},
    {"name": "Lisa (Blackpink)", "follower_count": 80, "profession": "Singer"},
    {"name": "Robert Downey Jr", "follower_count": 78, "profession": "Actor"},
    {"name": "Chris Hemsworth", "follower_count": 77, "profession": "Actor"},
    {"name": "Tom Holland", "follower_count": 76, "profession": "Actor"},
    {"name": "Zac Efron", "follower_count": 75, "profession": "Actor"},
    {"name": "Dua Lipa", "follower_count": 74, "profession": "Singer"},
    {"name": "Harry Styles", "follower_count": 73, "profession": "Singer"},
    {"name": "BTS Official", "follower_count": 72, "profession": "Music Group"},
    {"name": "Liza Koshy", "follower_count": 71, "profession": "YouTuber/Actress"},
    {"name": "Margot Robbie", "follower_count": 70, "profession": "Actress"},
    {"name": "Ryan Reynolds", "follower_count": 69, "profession": "Actor"},
    {"name": "Anne Hathaway", "follower_count": 68, "profession": "Actress"},
    {"name": "Liam Payne", "follower_count": 67, "profession": "Singer"},
    {"name": "Niall Horan", "follower_count": 66, "profession": "Singer"},
    {"name": "Louis Tomlinson", "follower_count": 65, "profession": "Singer"},
    {"name": "Zayn Malik", "follower_count": 64, "profession": "Singer"},
    {"name": "The Rock", "follower_count": 63, "profession": "Actor/Wrestler"},
    {"name": "John Cena", "follower_count": 62, "profession": "Wrestler/Actor"},
    {"name": "Stephen Curry", "follower_count": 61, "profession": "Basketball Player"},
    {"name": "Roger Federer", "follower_count": 60, "profession": "Tennis Player"},
    {"name": "Serena Williams", "follower_count": 59, "profession": "Tennis Player"},
    {"name": "Novak Djokovic", "follower_count": 58, "profession": "Tennis Player"},
    {"name": "Usain Bolt", "follower_count": 57, "profession": "Sprinter"},
    {"name": "Lewis Hamilton", "follower_count": 56, "profession": "Racing Driver"},
    {"name": "Conor McGregor", "follower_count": 55, "profession": "MMA Fighter"},
    {"name": "Floyd Mayweather", "follower_count": 54, "profession": "Boxer"},
    {"name": "Tom Brady", "follower_count": 53, "profession": "Football Player"},
    {"name": "Kevin Durant", "follower_count": 52, "profession": "Basketball Player"},
    {"name": "James Harden", "follower_count": 51, "profession": "Basketball Player"},
    {"name": "Giannis Antetokounmpo", "follower_count": 50, "profession": "Basketball Player"},
    {"name": "Luka Doncic", "follower_count": 49, "profession": "Basketball Player"},
    {"name": "Joel Embiid", "follower_count": 48, "profession": "Basketball Player"},
    {"name": "Nikola Jokic", "follower_count": 47, "profession": "Basketball Player"},
    {"name": "Damian Lillard", "follower_count": 46, "profession": "Basketball Player"},
    {"name": "Stephen Colbert", "follower_count": 45, "profession": "TV Host"},
    {"name": "Jimmy Fallon", "follower_count": 44, "profession": "TV Host"},
    {"name": "Trevor Noah", "follower_count": 43, "profession": "Comedian/TV Host"},
    {"name": "John Oliver", "follower_count": 42, "profession": "Comedian/TV Host"},
    {"name": "Conan O'Brien", "follower_count": 41, "profession": "Comedian/TV Host"},
    {"name": "James Corden", "follower_count": 40, "profession": "TV Host"},
    {"name": "Jimmy Kimmel", "follower_count": 39, "profession": "TV Host"},
    {"name": "Seth Meyers", "follower_count": 38, "profession": "TV Host"},
    {"name": "Andy Cohen", "follower_count": 37, "profession": "TV Host"},
    {"name": "Ryan Seacrest", "follower_count": 36, "profession": "TV Host"},
    {"name": "Dr. Phil", "follower_count": 35, "profession": "TV Personality"},
    {"name": "Ellen Pompeo", "follower_count": 34, "profession": "Actress"},
    {"name": "Sofia Vergara", "follower_count": 33, "profession": "Actress"},
    {"name": "Viola Davis", "follower_count": 32, "profession": "Actress"},
    {"name": "Reese Witherspoon", "follower_count": 31, "profession": "Actress"},
    {"name": "Jennifer Aniston", "follower_count": 30, "profession": "Actress"},
    {"name": "Sandra Bullock", "follower_count": 29, "profession": "Actress"},
    {"name": "Julia Roberts", "follower_count": 28, "profession": "Actress"},
    {"name": "Meryl Streep", "follower_count": 27, "profession": "Actress"},
    {"name": "Cate Blanchett", "follower_count": 26, "profession": "Actress"},
    {"name": "Nicole Kidman", "follower_count": 25, "profession": "Actress"},
    {"name": "Charlize Theron", "follower_count": 24, "profession": "Actress"},
    {"name": "Angelina Jolie", "follower_count": 23, "profession": "Actress"},
    {"name": "Scarlett Johansson", "follower_count": 22, "profession": "Actress"},
    {"name": "Jennifer Lawrence", "follower_count": 21, "profession": "Actress"},
    {"name": "Emma Stone", "follower_count": 20, "profession": "Actress"},
    {"name": "Natalie Portman", "follower_count": 19, "profession": "Actress"},
    {"name": "Anne Hathaway", "follower_count": 18, "profession": "Actress"}]
